/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Web3HubRouteImport } from './routes/web3-hub'
import { Route as MagnificRouteImport } from './routes/magnific'
import { Route as IndexRouteImport } from './routes/index'

const Web3HubRoute = Web3HubRouteImport.update({
  id: '/web3-hub',
  path: '/web3-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const MagnificRoute = MagnificRouteImport.update({
  id: '/magnific',
  path: '/magnific',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/magnific': typeof MagnificRoute
  '/web3-hub': typeof Web3HubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/magnific': typeof MagnificRoute
  '/web3-hub': typeof Web3HubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/magnific': typeof MagnificRoute
  '/web3-hub': typeof Web3HubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/magnific' | '/web3-hub'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/magnific' | '/web3-hub'
  id: '__root__' | '/' | '/magnific' | '/web3-hub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MagnificRoute: typeof MagnificRoute
  Web3HubRoute: typeof Web3HubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web3-hub': {
      id: '/web3-hub'
      path: '/web3-hub'
      fullPath: '/web3-hub'
      preLoaderRoute: typeof Web3HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magnific': {
      id: '/magnific'
      path: '/magnific'
      fullPath: '/magnific'
      preLoaderRoute: typeof MagnificRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MagnificRoute: MagnificRoute,
  Web3HubRoute: Web3HubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
